2023-04-18:21:38:28,721, Starting web crawler...
2023-04-18:21:38:28,721, Crawling: https://www.wtatennis.com/
2023-04-18:21:38:29,284, Finished crawling: https://www.wtatennis.com/
2023-04-18:21:38:29,284, Crawling: #main-content
2023-04-18:21:38:29,284, Failed to crawl: #main-content
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 107, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 76, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 100, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#main-content': No scheme supplied. Perhaps you meant https://#main-content?
2023-04-18:21:38:29,286, Crawling: apps
2023-04-18:21:38:29,286, Finished crawling: apps
2023-04-18:21:38:29,286, Crawling: http://instagram.com/wta
2023-04-18:21:38:30,524, Finished crawling: http://instagram.com/wta
2023-04-18:21:38:30,525, Crawling: http://www.usopenseries.com/home/default.sps
2023-04-18:21:38:31,286, Finished crawling: http://www.usopenseries.com/home/default.sps
2023-04-18:21:38:31,287, Crawling: #
2023-04-18:21:38:31,287, Failed to crawl: #
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 107, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 76, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 100, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#': No scheme supplied. Perhaps you meant https://#?
2023-04-18:21:38:31,288, Crawling: #maincontent
2023-04-18:21:38:31,288, Failed to crawl: #maincontent
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 107, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 76, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 100, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#maincontent': No scheme supplied. Perhaps you meant https://#maincontent?
2023-04-18:21:38:31,289, Crawling: http://t.email.usopen.org/lp/ustaProAcq
2023-04-18:21:38:31,759, Finished crawling: http://t.email.usopen.org/lp/ustaProAcq
2023-04-18:21:38:31,759, Crawling: #
2023-04-18:21:38:31,759, Failed to crawl: #
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 107, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 76, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 100, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#': No scheme supplied. Perhaps you meant https://#?
2023-04-18:21:38:31,760, Crawling: http://t.email.usopen.org/lp/ustaProAcq
2023-04-18:21:38:32,281, Finished crawling: http://t.email.usopen.org/lp/ustaProAcq
2023-04-18:21:38:32,281, Crawling: #
2023-04-18:21:38:32,281, Failed to crawl: #
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 107, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 76, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 100, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#': No scheme supplied. Perhaps you meant https://#?
2023-04-18:21:38:32,282, Crawling: http://www.atpworldtour.com/
2023-04-18:21:38:33,024, Finished crawling: http://www.atpworldtour.com/
2023-04-18:21:38:33,024, Crawling: #
2023-04-18:21:38:33,024, Failed to crawl: #
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 107, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 76, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 100, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#': No scheme supplied. Perhaps you meant https://#?
2023-04-18:21:38:33,025, Crawling: http://
2023-04-18:21:38:33,025, Failed to crawl: http://
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 107, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 76, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 100, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 445, in prepare_url
    raise InvalidURL(f"Invalid URL {url!r}: No host supplied")
requests.exceptions.InvalidURL: Invalid URL 'http://': No host supplied
2023-04-18:21:38:33,026, Crawling: http://
2023-04-18:21:38:33,026, Failed to crawl: http://
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 107, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 76, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 100, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 445, in prepare_url
    raise InvalidURL(f"Invalid URL {url!r}: No host supplied")
requests.exceptions.InvalidURL: Invalid URL 'http://': No host supplied
2023-04-18:21:38:33,027, Crawling: http://
2023-04-18:21:38:33,027, Failed to crawl: http://
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 107, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 76, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 100, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 445, in prepare_url
    raise InvalidURL(f"Invalid URL {url!r}: No host supplied")
requests.exceptions.InvalidURL: Invalid URL 'http://': No host supplied
2023-04-18:21:38:33,028, Crawling: http://barcelonaopenbancsabadell.com
2023-04-18:21:38:35,267, Finished crawling: http://barcelonaopenbancsabadell.com
2023-04-18:21:38:35,267, Crawling: #
2023-04-18:21:38:35,268, Failed to crawl: #
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 107, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 76, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 100, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#': No scheme supplied. Perhaps you meant https://#?
2023-04-18:21:38:35,268, Crawling: #
2023-04-18:21:38:35,269, Failed to crawl: #
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 107, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 76, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 100, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#': No scheme supplied. Perhaps you meant https://#?
2023-04-18:21:38:35,269, Crawling: #
2023-04-18:21:38:35,269, Failed to crawl: #
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 107, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 76, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 100, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#': No scheme supplied. Perhaps you meant https://#?
2023-04-18:21:38:35,270, Crawling: #
2023-04-18:21:38:35,270, Failed to crawl: #
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 107, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 76, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 100, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#': No scheme supplied. Perhaps you meant https://#?
2023-04-18:21:38:35,271, Crawling: #page
2023-04-18:21:38:35,271, Failed to crawl: #page
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 107, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 76, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 100, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#page': No scheme supplied. Perhaps you meant https://#page?
2023-04-18:21:38:35,272, Crawling: #pll_switcher
2023-04-18:21:38:35,272, Failed to crawl: #pll_switcher
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 107, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 76, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 100, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#pll_switcher': No scheme supplied. Perhaps you meant https://#pll_switcher?
2023-04-18:21:38:35,274, Crawling: http://barcelonaopenbancsabadell.com/aviso-legal
2023-04-18:21:38:35,274, Finished crawling: http://barcelonaopenbancsabadell.com/aviso-legal
2023-04-18:21:38:35,274, Crawling: http://barcelonaopenbancsabadell.com/hospitality
2023-04-18:21:38:37,035, Finished crawling: http://barcelonaopenbancsabadell.com/hospitality
2023-04-18:21:38:37,035, Crawling: #
2023-04-18:21:38:37,036, Failed to crawl: #
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 107, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 76, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 100, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#': No scheme supplied. Perhaps you meant https://#?
2023-04-18:21:38:37,036, Crawling: #
2023-04-18:21:38:37,037, Failed to crawl: #
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 107, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 76, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 100, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#': No scheme supplied. Perhaps you meant https://#?
2023-04-18:21:38:37,037, Crawling: #
2023-04-18:21:38:37,037, Failed to crawl: #
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 107, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 76, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 100, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#': No scheme supplied. Perhaps you meant https://#?
2023-04-18:21:38:37,038, Crawling: #
2023-04-18:21:38:37,038, Failed to crawl: #
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 107, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 76, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 100, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#': No scheme supplied. Perhaps you meant https://#?
2023-04-18:21:38:37,039, Crawling: #page
2023-04-18:21:38:37,039, Failed to crawl: #page
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 107, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 76, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 100, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#page': No scheme supplied. Perhaps you meant https://#page?
2023-04-18:21:38:37,040, Crawling: #pll_switcher
2023-04-18:21:38:37,040, Failed to crawl: #pll_switcher
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 107, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 76, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 100, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#pll_switcher': No scheme supplied. Perhaps you meant https://#pll_switcher?
2023-04-18:21:38:37,041, Crawling: http://barcelonaopenbancsabadell.com/noticias
2023-04-18:21:38:39,952, Finished crawling: http://barcelonaopenbancsabadell.com/noticias
2023-04-18:21:38:39,952, Crawling: #
2023-04-18:21:38:39,953, Failed to crawl: #
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 107, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 76, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 100, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#': No scheme supplied. Perhaps you meant https://#?
2023-04-18:21:38:39,954, Crawling: #
2023-04-18:21:38:39,954, Failed to crawl: #
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 107, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 76, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 100, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#': No scheme supplied. Perhaps you meant https://#?
2023-04-18:21:38:39,955, Crawling: #
2023-04-18:21:38:39,955, Failed to crawl: #
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 107, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 76, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 100, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#': No scheme supplied. Perhaps you meant https://#?
2023-04-18:21:38:39,956, Crawling: #
2023-04-18:21:38:39,956, Failed to crawl: #
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 107, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 76, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 100, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#': No scheme supplied. Perhaps you meant https://#?
2023-04-18:21:38:39,957, Crawling: #page
2023-04-18:21:38:39,957, Failed to crawl: #page
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 107, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 76, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 100, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#page': No scheme supplied. Perhaps you meant https://#page?
2023-04-18:21:38:39,958, Crawling: #pll_switcher
2023-04-18:21:38:39,958, Failed to crawl: #pll_switcher
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 107, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 76, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 100, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#pll_switcher': No scheme supplied. Perhaps you meant https://#pll_switcher?
2023-04-18:21:38:39,959, Crawling: http://barcelonaopenbancsabadell.com/tickets
2023-04-18:21:38:41,835, Finished crawling: http://barcelonaopenbancsabadell.com/tickets
2023-04-18:21:38:41,835, Crawling: #
2023-04-18:21:38:41,835, Failed to crawl: #
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 107, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 76, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 100, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#': No scheme supplied. Perhaps you meant https://#?
2023-04-18:21:38:41,836, Crawling: #
2023-04-18:21:38:41,836, Failed to crawl: #
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 107, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 76, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 100, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#': No scheme supplied. Perhaps you meant https://#?
2023-04-18:21:38:41,837, Crawling: #
2023-04-18:21:38:41,837, Failed to crawl: #
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 107, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 76, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 100, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#': No scheme supplied. Perhaps you meant https://#?
2023-04-18:21:38:41,838, Crawling: #
2023-04-18:21:38:41,838, Failed to crawl: #
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 107, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 76, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 100, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#': No scheme supplied. Perhaps you meant https://#?
2023-04-18:21:38:41,839, Crawling: #page
2023-04-18:21:38:41,839, Failed to crawl: #page
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 107, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 76, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 100, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#page': No scheme supplied. Perhaps you meant https://#page?
2023-04-18:21:38:41,840, Crawling: #pll_switcher
2023-04-18:21:38:41,840, Failed to crawl: #pll_switcher
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 107, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 76, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 100, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#pll_switcher': No scheme supplied. Perhaps you meant https://#pll_switcher?
2023-04-18:21:38:41,841, Crawling: http://https://www.tennisclubroseto.it/atp.html
2023-04-18:21:38:41,847, Failed to crawl: http://https://www.tennisclubroseto.it/atp.html
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/Cellar/python@3.11/3.11.2/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python@3.11/3.11.2/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.11/3.11.2/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.11/3.11.2/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python@3.11/3.11.2/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 975, in send
    self.connect()
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x117286ad0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='https', port=80): Max retries exceeded with url: //www.tennisclubroseto.it/atp.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x117286ad0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 107, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 76, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 100, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='https', port=80): Max retries exceeded with url: //www.tennisclubroseto.it/atp.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x117286ad0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-04-18:21:38:41,851, Crawling: http://oeirasopen.pt/home
2023-04-18:21:38:44,095, Finished crawling: http://oeirasopen.pt/home
2023-04-18:21:38:44,096, Crawling: http://oeirasopen.pt/comochegar
2023-04-18:21:38:45,266, Finished crawling: http://oeirasopen.pt/comochegar
2023-04-18:21:38:45,267, Crawling: http://oeirasopen.pt/comochegar
2023-04-18:21:38:45,267, Finished crawling: http://oeirasopen.pt/comochegar
2023-04-18:21:38:45,267, Crawling: http://oeirasopen.pt/home
2023-04-18:21:38:46,613, Finished crawling: http://oeirasopen.pt/home
2023-04-18:21:38:46,613, Crawling: http://oeirasopen.pt/home
2023-04-18:21:38:48,792, Finished crawling: http://oeirasopen.pt/home
2023-04-18:21:38:48,792, Crawling: http://oeirasopen.pt/home
2023-04-18:21:38:50,346, Finished crawling: http://oeirasopen.pt/home
2023-04-18:21:38:50,346, Crawling: http://oeirasopen.pt/home
2023-04-18:21:38:52,826, Finished crawling: http://oeirasopen.pt/home
2023-04-18:21:38:52,826, Crawling: http://oeirasopen.pt/home
2023-04-18:21:38:54,750, Finished crawling: http://oeirasopen.pt/home
2023-04-18:21:38:54,750, Crawling: http://oeirasopen.pt/home
2023-04-18:21:38:58,159, Finished crawling: http://oeirasopen.pt/home
2023-04-18:21:38:58,159, Crawling: http://oeirasopen.pt/home
