2023-04-18:22:06:48,597, Starting web crawler...
2023-04-18:22:06:48,597, Crawling: https://www.wtatennis.com/
2023-04-18:22:06:48,870, Finished crawling: https://www.wtatennis.com/
2023-04-18:22:06:48,870, Failed to crawl: https://www.wtatennis.com/
Traceback (most recent call last):
  File "web_crawler.py", line 120, in run_crawler
    time.sleep(0.2)
NameError: name 'time' is not defined
2023-04-18:22:06:48,870, Crawling: apps
2023-04-18:22:06:48,871, Failed to crawl: apps
Traceback (most recent call last):
  File "web_crawler.py", line 116, in run_crawler
    self.crawl_url(url)
  File "web_crawler.py", line 82, in crawl_url
    html = self.get_url_info(url)
  File "web_crawler.py", line 107, in get_url_info
    return requests.get(url).text
  File "/opt/anaconda3/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/anaconda3/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/opt/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 449, in prepare_request
    p.prepare(
  File "/opt/anaconda3/lib/python3.8/site-packages/requests/models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "/opt/anaconda3/lib/python3.8/site-packages/requests/models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'apps': No schema supplied. Perhaps you meant http://apps?
2023-04-18:22:06:48,872, Crawling: http://instagram.com/wta
2023-04-18:22:06:49,922, Finished crawling: http://instagram.com/wta
2023-04-18:22:06:49,922, Failed to crawl: http://instagram.com/wta
Traceback (most recent call last):
  File "web_crawler.py", line 120, in run_crawler
    time.sleep(0.2)
NameError: name 'time' is not defined
2023-04-18:22:06:49,923, Crawling: http://www.usopenseries.com/home/default.sps
2023-04-18:22:06:50,059, Finished crawling: http://www.usopenseries.com/home/default.sps
2023-04-18:22:06:50,060, Failed to crawl: http://www.usopenseries.com/home/default.sps
Traceback (most recent call last):
  File "web_crawler.py", line 120, in run_crawler
    time.sleep(0.2)
NameError: name 'time' is not defined
2023-04-18:22:06:50,060, Crawling: http://t.email.usopen.org/lp/ustaProAcq
2023-04-18:22:06:50,437, Finished crawling: http://t.email.usopen.org/lp/ustaProAcq
2023-04-18:22:06:50,437, Failed to crawl: http://t.email.usopen.org/lp/ustaProAcq
Traceback (most recent call last):
  File "web_crawler.py", line 120, in run_crawler
    time.sleep(0.2)
NameError: name 'time' is not defined
2023-04-18:22:06:50,437, Crawling: http://t.email.usopen.org/lp/ustaProAcq
2023-04-18:22:06:50,437, Finished crawling: http://t.email.usopen.org/lp/ustaProAcq
2023-04-18:22:06:50,437, Failed to crawl: http://t.email.usopen.org/lp/ustaProAcq
Traceback (most recent call last):
  File "web_crawler.py", line 120, in run_crawler
    time.sleep(0.2)
NameError: name 'time' is not defined
2023-04-18:22:06:50,437, Crawling: http://www.atpworldtour.com/
2023-04-18:22:06:50,922, Finished crawling: http://www.atpworldtour.com/
2023-04-18:22:06:50,923, Failed to crawl: http://www.atpworldtour.com/
Traceback (most recent call last):
  File "web_crawler.py", line 120, in run_crawler
    time.sleep(0.2)
NameError: name 'time' is not defined
2023-04-18:22:06:50,923, Crawling: http://
2023-04-18:22:06:50,923, Failed to crawl: http://
Traceback (most recent call last):
  File "web_crawler.py", line 116, in run_crawler
    self.crawl_url(url)
  File "web_crawler.py", line 82, in crawl_url
    html = self.get_url_info(url)
  File "web_crawler.py", line 107, in get_url_info
    return requests.get(url).text
  File "/opt/anaconda3/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/anaconda3/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/opt/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 449, in prepare_request
    p.prepare(
  File "/opt/anaconda3/lib/python3.8/site-packages/requests/models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "/opt/anaconda3/lib/python3.8/site-packages/requests/models.py", line 391, in prepare_url
    raise InvalidURL("Invalid URL %r: No host supplied" % url)
requests.exceptions.InvalidURL: Invalid URL 'http://': No host supplied
2023-04-18:22:06:50,924, Crawling: http://
2023-04-18:22:06:50,924, Finished crawling: http://
2023-04-18:22:06:50,924, Failed to crawl: http://
Traceback (most recent call last):
  File "web_crawler.py", line 120, in run_crawler
    time.sleep(0.2)
NameError: name 'time' is not defined
2023-04-18:22:06:50,924, Crawling: http://
2023-04-18:22:06:50,924, Finished crawling: http://
2023-04-18:22:06:50,924, Failed to crawl: http://
Traceback (most recent call last):
  File "web_crawler.py", line 120, in run_crawler
    time.sleep(0.2)
NameError: name 'time' is not defined
2023-04-18:22:06:50,924, Crawling: http://barcelonaopenbancsabadell.com
2023-04-18:22:06:52,568, Finished crawling: http://barcelonaopenbancsabadell.com
2023-04-18:22:06:52,569, Failed to crawl: http://barcelonaopenbancsabadell.com
Traceback (most recent call last):
  File "web_crawler.py", line 120, in run_crawler
    time.sleep(0.2)
NameError: name 'time' is not defined
2023-04-18:22:06:52,569, Crawling: http://barcelonaopenbancsabadell.com/aviso-legal
2023-04-18:22:06:53,733, Finished crawling: http://barcelonaopenbancsabadell.com/aviso-legal
2023-04-18:22:06:53,734, Failed to crawl: http://barcelonaopenbancsabadell.com/aviso-legal
Traceback (most recent call last):
  File "web_crawler.py", line 120, in run_crawler
    time.sleep(0.2)
NameError: name 'time' is not defined
2023-04-18:22:06:53,734, Crawling: http://barcelonaopenbancsabadell.com/hospitality
2023-04-18:22:06:55,039, Finished crawling: http://barcelonaopenbancsabadell.com/hospitality
2023-04-18:22:06:55,040, Failed to crawl: http://barcelonaopenbancsabadell.com/hospitality
Traceback (most recent call last):
  File "web_crawler.py", line 120, in run_crawler
    time.sleep(0.2)
NameError: name 'time' is not defined
2023-04-18:22:06:55,040, Crawling: http://barcelonaopenbancsabadell.com/noticias
2023-04-18:22:06:57,859, Finished crawling: http://barcelonaopenbancsabadell.com/noticias
2023-04-18:22:06:57,859, Failed to crawl: http://barcelonaopenbancsabadell.com/noticias
Traceback (most recent call last):
  File "web_crawler.py", line 120, in run_crawler
    time.sleep(0.2)
NameError: name 'time' is not defined
2023-04-18:22:06:57,859, Crawling: http://barcelonaopenbancsabadell.com/tickets
